# Generated by Django 4.0.4 on 2022-04-18 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_client_last_payment_date'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.pair'),
        ),
        migrations.AddField(
            model_name='signal',
            name='raw_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signal',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 23, 9, 59, 900086)),
        ),
        migrations.AddField(
            model_name='signal',
            name='timeframe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='type',
            field=models.CharField(choices=[('BULL', 'BULL'), ('BEAR', 'BEAR')], max_length=10, null=True),
        ),
    ]
