# Generated by Django 4.0.4 on 2022-04-18 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_signal_pair_signal_raw_text_signal_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 23, 26, 37, 788681)),
        ),
    ]
