# Generated by Django 4.0.4 on 2022-04-20 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_timeframe_alter_client_last_payment_date_and_more'),
        ('api', '0003_alter_signal_received_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='signal',
            name='pair_with_timeframe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.pairwithtimeframe'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 19, 3, 14, 276588)),
        ),
    ]
