# Generated by Django 4.0.4 on 2022-04-20 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_signal_pair_remove_signal_timeframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 19, 26, 10, 199577)),
        ),
    ]
