# Generated by Django 4.0.4 on 2022-04-20 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_signal_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 19, 40, 52, 86924)),
        ),
    ]
