# Generated by Django 4.0.4 on 2022-04-21 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_signal_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 15, 24, 6, 253699)),
        ),
    ]
