# Generated by Django 4.0.4 on 2022-04-18 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=300, null=True)),
                ('provider_token', models.CharField(default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('message_template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PairGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('display_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('display_name', models.CharField(max_length=1000)),
                ('duration', models.DurationField(default=datetime.timedelta(days=30))),
                ('cost', models.FloatField(default=0)),
                ('currency', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('display_name', models.CharField(max_length=1000)),
                ('message_template', models.CharField(max_length=1000)),
                ('pair_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.pairgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('telegram_nick', models.CharField(max_length=1000, null=True)),
                ('last_payment_date', models.DateTimeField(default=datetime.datetime(2022, 4, 18, 18, 41, 26, 403985))),
                ('payment_expire_date', models.DateTimeField(null=True)),
                ('pairs', models.ManyToManyField(to='bot.pair')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.tariff')),
            ],
        ),
    ]
