# Generated by Django 4.0.4 on 2022-04-18 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_tariff_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 22, 14, 24, 578262)),
        ),
        migrations.AlterField(
            model_name='client',
            name='pairs',
            field=models.ManyToManyField(related_name='clients', to='bot.pair'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='pair_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairs', to='bot.pairgroup'),
        ),
    ]
