# Generated by Django 4.0.4 on 2022-04-18 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_client_last_payment_date_alter_client_pairs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='message_template',
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 0, 18, 40, 982788)),
        ),
    ]
