# Generated by Django 4.0.4 on 2022-04-18 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_pair_message_template_client_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 0, 22, 47, 510619)),
        ),
    ]
